load("@aspect_rules_js//js:defs.bzl", "js_library")

js_library(
    name = "a",
    srcs = [
        "main.js",
    ],
    deps = [
        "//:node_modules/lodash"
    ],
    visibility = ["//visibility:public"],
)
