load("//minimalist_rules_js:defs.bzl", "npm_link_all_packages", "run_js_binary")

npm_link_all_packages(
    name = "node_modules",
)

run_js_binary(
    name = "bundle",
    srcs = [
        "src/main.js",
    ],
    outs = ["bundle.js"],
    args = [
        "--preserve-symlinks",
        "--format=esm",
        "--bundle",
        "$${EXECROOT}/$(location :src/main.js)",
        "--outfile=$${EXECROOT}/$(location :bundle.js)",
    ],
    data = [
        "//package/a_lib",
    ],
    env = {
        "CWD_FILE": "$${EXECROOT}/$(location :package.json)",
        "SYMLINKS": "$${BINDIR}/package/a_lib:$${EXECROOT}/$(location :node_modules)/@surma/a_lib_with_workspace_deps",
    },
    is_npx = True,
    node_modules = ":node_modules",
    tool = "esbuild",
)

filegroup(
    name = "a_lib_with_workspace_deps",
    srcs = [
        "package.json",
        ":bundle",
    ],
    visibility = ["//visibility:public"],
)
